  0%|                                                                                                         | 0/772 [00:00<?, ?it/s]/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py:61: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
{'loss': 2.6337, 'learning_rate': 8.333333333333334e-06, 'epoch': 0.01}
/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py:1652: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  total_norm_cuda = get_accelerator().FloatTensor([float(total_norm)])
  0%|                                                                                               | 1/772 [00:20<4:25:28, 20.66s/it]

  0%|▏                                                                                              | 2/772 [00:40<4:17:24, 20.06s/it]

  0%|▎                                                                                              | 3/772 [01:00<4:15:48, 19.96s/it]

  1%|▍                                                                                              | 4/772 [01:19<4:11:47, 19.67s/it]

  1%|▌                                                                                              | 5/772 [01:38<4:07:51, 19.39s/it]
LoRA 参数已保存到 /data/SyL/Event_RGB/checkpoints/llava-v1.5-7b-instruction/tmp-checkpoint-5/lora_parameters.pth
  1%|▌                                                                                              | 5/772 [01:38<4:07:51, 19.39s/it]Traceback (most recent call last):
  File "/data/SyL/Event_RGB/deepspeed_train.py", line 126, in <module>
    trainer.train()
  File "/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2302, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2378, in _save_checkpoint
    self.save_model(staging_output_dir, _internal_call=True)
  File "/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2873, in save_model
    self._save(output_dir, state_dict=state_dict)
  File "/home/user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2958, in _save
    self.model.save_pretrained(
  File "/data/SyL/Event_RGB/model/EventChatModel.py", line 177, in save_pretrained
    self.save_model(save_directory)
  File "/data/SyL/Event_RGB/model/EventChatModel.py", line 161, in save_model
    peft_config.save_pretrained(output_dir)
AttributeError: 'dict' object has no attribute 'save_pretrained'